name: Publish

on:
  release:
    types: [published]

jobs:
  npm:
    name: Publish npm
    uses: ./.github/workflows/publish-npm.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  vscode:
    name: Publish VS Code
    uses: ./.github/workflows/publish-vscode.yml
    permissions:
      contents: write
    secrets:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
      OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
